### PR TITLE
Blog Page of MedFlare

### LINKED ISSUE #18: MedFlare: Make a "Blogs" Page with Blog Cards
Hey JWOC participants, good to see you.

Build a MedFlare Blog Page with multiple cards that have some text block and accompanying images. Follow the following as a part of your checklist.

- Make sure that the images you use are uncopyrighted (Some sources are [Pexels](https://www.pexels.com/), [Pixabay](https://pixabay.com/), [Unsplash](https://unsplash.com/images) ).
- Use MedFlare relevant text and images (feel free to use your creativity)
- Make sure that Blog is linked in all correct places (navbar, footer, etc.)

Feel free to use the below link as a reference:
[Blog Top 50](https://detailed.com/50/)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by zugzwang03**
#18 issue about making a blog page concerning the services offered and also created some empty blog pages to get redirected to the specific services.

- Info about the related issue 

- [x] JWOC Participant
- [x] Contributor

Closes: #18 

### Describe the changes you've made
changed the Services sector of the website with blog cards

Give a clear description what modifications you have made
created 6 cards concerning the services offered in MedFlare
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
servic1
service2

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by zugzwang03** [comment]
https://zugzwang03.github.io/MedFlare/ is the link to the modified website now.

**Comment by prathimacode-hub** [comment]
@zugzwang03 Order of a page turned into a shuffle. Once check it up.

**Comment by zugzwang03** [comment]
Ma'am, I made some changes, can you check now?

**Comment by zugzwang03** [comment]
Ma'am, I did what was assigned to me, so can't this PR be labelled, merged and closed?

**Comment by prathimacode-hub** [comment]
> Ma'am, I did what was assigned to me, so can't this PR be labelled, merged and closed?

Ok, I shall check it. @zugzwang03

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Welcome to repo. Great start. Keep it up. Congrats. 🎉👏@zugzwang03

**Pull request merged**
