### PR TITLE
Improved the Bed Availability Notification Form

### LINKED ISSUE #56: Improve the Design of Bed Availability Notification Form Page
## Issue 
The form is really bad and is overlapping the image on the left. It is also not reponsive

## Screenshot
image

## Solution 
I can work on this issue and improve the UI of the form very much +  Make it responsive also

### PR DESCRIPTION
**Pull request by 3xp11i**
- [x] Hacktoberfest Participant
- [ ] Contributor

Closes: #56 number that will be closed through this PR

### Describe the changes you've made

This commit will improve the UI of
the Bed Availability Notification Form page
and also make it responsive.

Give a clear description what modifications you have made

- I have changed the HTML code of the page and divided it into various divs to apply my CSS
- I have changed the CSS file of the page, added media queries, and removed some unnecessary code from it.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I used my chrome dev tools to test if its responsive or not.

Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
[Original Page](https://user-images.githubusercontent.com/65062036/194871511-9511b639-13ba-4e6c-b6ae-20bb3f787406.mp4) | [Updated Page](https://user-images.githubusercontent.com/65062036/194871692-3d614e8a-e46c-48f9-86bf-39409c70ebac.mp4) |

### CODE REVIEW

**Comment by 3xp11i** [comment]
Check it out @prathimacode-hub !

**Review by Rishikavishnoi — COMMENTED** [review]
@prakhartiwari0 also add a screenshot of the updated page

**Comment by 3xp11i** [comment]
> @prakhartiwari0 also add a screenshot of the updated page

Here it is...

image

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@prakhartiwari0 your branch has a conflict, firstly solve it from your end.

**Comment by 3xp11i** [comment]
@Rishikavishnoi The project has suddenly migrated to react based project, how can I make changes to the CSS now?

**Comment by 3xp11i** [comment]
Should I make changes to the css files in `old` directory?

**Comment by Rishikavishnoi** [comment]
@prakhartiwari0  Firstly update the repo in your local system, and them  do same changes in CSS file in old directory.

**Comment by 3xp11i** [comment]
@Rishikavishnoi I have created one more PR kindly check #63

**Pull request closed without merging**
