### PR TITLE
Header section with navbar added

### LINKED ISSUE #7: MedFlare : Create a Header Section of Home Page
Hey JWOC participants, good to see you.

This issue's goal is to create a header section of home page which also includes Navigation bar of medical webapp

Feel free to be creative! And please take care of the following criteria:

- create header along with Navigation Bar with 6 options
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of  header on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by soujo**
## Related Issue 

- Info about the related issue 

- [x] JWOC Participant
- [ ] Contributor

Closes: #7

### Describe the changes you've made

- Added header section with navbar 
- Designed for the same
- Added necessary images for the same

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested the website locally in my machine and also have consulted to my mentor, she approved my design

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original :
 
 There was no section previously 

 Updated : 

Screenshot (190)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add the [PR template](https://github.com/prathimacode-hub/MedFlare/blob/main/.github/PULL_REQUEST_TEMPLATE.md), along with what is added in PR and issue number you allotted to. you can add so using edit option here in PR message. @soujo

**Comment by soujo** [comment]
@prathimacode-hub , I have made the changes. Kindly look through it

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. Welcome to the repo. This was a great start. Keep it up. 🎉👏@soujo

**Comment by prathimacode-hub** [comment]
Only change it needs, is merge your code of index.html in existing /Home page/index.html since this has only 3 sections, you can include your header and nav bar there. Images let it be as it is. And style.css. keep it out in main instead of inside Home page. So that work you had done is reflected properly. Let me know, once you do and it's ready to be merged then. @soujo

**Comment by soujo** [comment]
@prathimacode-hub , the code of header section in already in index.html of Home page folder and I didn't got the point about style.css, could you again clarify that please

**Comment by prathimacode-hub** [comment]
Can you drop me a message in discord. Discussion would be much better to clear up things. @soujo

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. Welcome to repo. Great start. Kudos to you. Well done. 🎉👏@soujo

**Pull request merged**
