### PR TITLE
Make the navbar buttons work

### LINKED ISSUE #49: Clicking on Navbar Buttons does nothing.
Clicking on Navbar buttons(Home, About Us, Services...) should take them to their respective sections which is not happening.

home

### PR DESCRIPTION
**Pull request by 3xp11i**
- [x] Hacktoberfest Participant
- [ ] Contributor

Closes: #49

### Describe the changes you've made
- Assigned ids to the main sections of the website
- Gave the `href` attribute of all the navbar buttons their respective section's id to make that button redirect to that specific section when clicked.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I simply clicked each button of the navbar to check if they are redirecting me to the correct sections according to their names or not.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
[Screencast from 04-10-22 07:30:27 PM IST.webm](https://user-images.githubusercontent.com/65062036/193840036-7887867f-7324-42b9-bb36-ab63528f592f.webm) | https://user-images.githubusercontent.com/65062036/193840980-9ecb60d7-1c3f-4908-8696-c95940d78acb.mp4 |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Don't directly create a PR without creating an issue and getting it assigned. @prakhartiwari0

**Comment by prathimacode-hub** [comment]
Can you add the other design changes you had thought of doing it to this PR? @prakhartiwari0

**Comment by 3xp11i** [comment]
> Can you add the other design changes you had thought of doing it to this PR? @prakhartiwari0

If you can tell me what kind of design changes you want, I will add them. But as of now, I don't think the navbar needs many changes. Maybe we could make the underline animation a little faster, and make the navbar's position fixed. But that's not much of an issue.

**Comment by prathimacode-hub** [comment]
Why have you closed it? @prakhartiwari0

**Comment by 3xp11i** [comment]
> Why have you closed it? @prakhartiwari0

The issue this PR was solving, is actually solved in #66. You said that raising only this issue (that is #49 ) is not [legible](https://github.com/prathimacode-hub/MedFlare/issues/49#issuecomment-1267951763), so I raised another issue (#57 ) which included more problems related to the home page.

**Pull request closed without merging**
