### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by Ardent10**
## Related Issue #67 

- Info about the related issue 

- [x] Hacktoberfest Participant
- [x] Contributor

Closes: #issue number that will be closed through this PR

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
Old: No Footer Component | New

PS: Conflicts will be resolved once the other PR is merged.

### CODE REVIEW

**Review by Rishikavishnoi — APPROVED** [review]
@Ardent10  Good work👍 
 but firstly, resolve the conflict by your side.

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
Resolve conflict

**Comment by Ardent10** [comment]
> @Ardent10 Good work👍 but firstly, resolve the conflict by your side.

This will be resolved only if the other PR is merged, it is because those changes are currently not on main of this repo. So when that is accepted I will resolve this one and commit once more.

**Comment by Ardent10** [comment]
@Rishikavishnoi There are no more conflicts now. it can be merged.

**Pull request merged**
