### PR TITLE
home page of the website

### LINKED ISSUE #1: MedFlare : Create Home Page  for Website
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of a home page of the website.

Feel free to be creative! And please take care of the following criteria:

- In the page, add About (uncopyrighted image along with introductory text), Services (6) and Why Choose Us (some pointers with intended graphics) sections excluding header and footer

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by soumali28**
## Home page of the website

- Adding the sections to the home page

- [x] JWOC Participant

Closes: #1

### Describe the changes you've made
I have created the 3sections about services and why us.

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

https://user-images.githubusercontent.com/66300439/152016943-36f1e222-4aa5-4bb3-876e-976322d3b4dd.mp4

MedFlare - Google Chrome 2_1_2022 10_44_17 PM

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Can you add the screenshot images of Services and Why Us too? @soumali28

**Comment by soumali28** [comment]
> Can you add the screenshot images of Services and Why Us too? @soumali28 

I have provided  the vid of the entire page

**Comment by prathimacode-hub** [comment]
> > Can you add the screenshot images of Services and Why Us too? @soumali28
> 
> I have provided the vid of the entire page

Just checked it. @soumali28

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. It's approved. This was a great start. More to go. Keep it up. 👏🎉@soumali28

**Comment by prathimacode-hub** [comment]
> > Can you add the screenshot images of Services and Why Us too? @soumali28
> 
> I have provided the vid of the entire page

Correct your issue number in PR template before merging @soumali28

**Pull request merged**
