### PR TITLE
Created a contact page with modern UI which includes responsive dedesign

### LINKED ISSUE #5: MedFlare : Create Contact Section for Website
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of contact page of the website.

Feel free to be creative! And please take care of the following criteria:

- In the page, add an embedded map with dummy location
- Include textual contact details along with contact form on to the right 

You can refer this link : http://cpconsol.com/contact-us.html

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by combatantash**
## Related Issue 

- Info about the related issue 

- [x] JWOC Participant
- [x] Contributor

Closes: #5 

### Describe the changes you've made
I have created a contact page with contact form, contact information and Google Map API and added media query for responsive design.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
On a local server

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

contact

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
This is contact related files. Create a sub repo of "Contact Page" and drop these files over there. This is not a home page index.html  to include directly in main repo.  @combatantash

**Comment by prathimacode-hub** [comment]
Don't close the PR for any correction, instead do the corrections over the forked repo and push it back while removing the earlier files. It updates the same. @combatantash

**Comment by combatantash** [comment]
will do the needful.

**Comment by prathimacode-hub** [comment]
I couldn't see the contact page files in your PR @combatantash

**Comment by combatantash** [comment]
i have generated new pull request with submodule added

**Pull request closed without merging**
